services:
  minio:
    container_name: minio_matcha_wallet
    image: minio/minio:latest
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio:/data
    networks:
      - app-tier
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address :9001

  gin:
    container_name: gin_matcha_wallet
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - gin:/src
    ports:
      - 3000:3000
    networks:
      - app-tier
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_ENDPOINT: http://minio:9000
      MINIO_BUCKET_NAME: ${MINIO_BUCKET_NAME}
      SECRET: ${SECRET}
      PSQL_CONNECTION_SETTINGS: ${PSQL_CONNECTION_SETTINGS}
    depends_on:
      - postgres
      - minio

  postgres:
    container_name: postgres_matcha_wallet
    volumes:
      - postgres:/var/lib/postgresql/data
    image: postgres:latest
    restart: always
    networks:
      - app-tier
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5433:5432

volumes:
  minio:
    driver: local
  postgres:
  gin:

networks:
  app-tier:
    driver: bridge
